### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by Fengzidalaoban** [xinyunaha/icveHelper#1]
怎么联系你

**Comment by xinyunaha** [comment]
> 怎么联系你

请贴一下错误截图

**Comment by Fengzidalaoban** [comment]
QQ:2524210044
备注：github




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xinyunaha"<notifications@github.com&gt;; 
发送时间: 2020年12月16日(星期三) 晚上9:55
收件人: "xinyunaha/icveHelper"<icveHelper@noreply.github.com&gt;; 
抄送: "深井#"<2524210044@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xinyunaha/icveHelper] 运行不了 (#1)





  
怎么联系你
  
请贴一下错误截图

**Comment by Fengzidalaoban** [comment]
附上视频




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xinyunaha/icveHelper"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月16日(星期三) 晚上9:55
收件人:&nbsp;"xinyunaha/icveHelper"<icveHelper@noreply.github.com&gt;;
抄送:&nbsp;"深井#"<2524210044@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xinyunaha/icveHelper] 运行不了 (#1)





  
怎么联系你
  
请贴一下错误截图
