### ISSUE TITLE
有点问题

### ISSUE THREAD

**Issue by ghost** [xinyunaha/icveHelper#2]
我本地测试不太行是不是有点问题跑python

**Comment by xinyunaha** [comment]
> 我本地测试不太行是不是有点问题跑python

如果有报错信息的话，请贴一下报错信息以方便解决

**Comment by ghost** [comment]
python icve_www.py  后出现验证码，但是提示密码不能为空，编辑py账号密码后却用不成。弹出验证码后一直在加载

**Comment by ghost** [comment]
有Q或者vx方便加一下好友吗

**Comment by xinyunaha** [comment]
> 有Q或者vx方便加一下好友吗

加个tg吧https://t.me/xinyunlk
