### ISSUE TITLE
mooc选完课程以后列出章节就没有动静了

### ISSUE THREAD

**Issue by Pessimisticc** [xinyunaha/icveHelper#3]

**Comment by xinyunaha** [comment]
课程发我一下，我这边抽空看看tg:@xinyunlk

**Comment by 1449362433** [comment]
运行成功但是进度条没有变化

**Comment by xinyunaha** [comment]
> 运行成功但条没有变化

详细说明一下情况，或者直接给课程链接我测试一下

**Comment by 1449362433** [comment]
![捕获](https://user-images.githubusercontent.com/87021276/134520157-0a4e148d-23f3-4184-9b64-140a2242c7cd.PNG)
这个是图片
这个是课程链接：https://mooc.icve.com.cn/study/myCourse/myCourse.html?courseOpenId=ltjcag2tg7nhj20qsxkmrw
